import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import SmoothScrollProvider from "@/components/common/SmoothScrollProvider";
import { ClientProvider } from "@/components/common/ClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <SmoothScrollProvider />
      <body className={inter.className}>
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
